name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  continuous_integration:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:

    - name: Check out Latest Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
        architecture: x64

    - name: Install Poetry
      uses: snok/install-poetry@v1.3
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Show poetry env info
      run: |
        poetry env info
        poetry config --list

    - name: Cache poetry venv
      uses: actions/cache@v3
      id: poetry-cache
      with:
        path: .venv
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
         ${{ runner.os }}-poetry-venv

    - name: Install Dependencies
      if: steps.poetry-cache.outputs.cache-hit != 'true'
      run: poetry install

    - name: Run Linting
      run: make lint

    - name: Run Tests
      run: make test
